spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:init.sql';DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
    data-username:
    data-password:

  jpa:
    open-in-view: true
    show_sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          fetch_size: 100
        use_lazy_proxy_factory: true
        enable_lazy_load_no_trans: true

server:
  port: 8080
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

jwt:
  header: Authorization
  secret: film
  expiration: 604800