export const MAIN_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const FILM_INFO = '/imdbId'
export const FAVORITE_FILMS = '/favorites'
