url:
  zuul:
    core: 'http://core:8081/'

spring:
  application:
    name: app-films-catalog-gateway
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  mandatory-file-encoding: UTF-8

server:
  port: 8080
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

management:
  server:
    port: { server.port }

zuul:
  routes:
    core:
      path: /core/**
      url: ${url.zuul.core}
      sensitive-headers:
